### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by samtuke** [jonata/Inkscape-OUTPUT-PRO#1]
OutputPro would be more useful if it was in English - translations have apparently already been made (see http://www.inkscapeforum.com/viewtopic.php?f=11&t=5943&start=25#p48245).

Can you please work to implement an English interface? OutputPro will reach a lot more people that way.

**Comment by jonata** [comment]
Done in 068d0c057982c453cd897f9e6cc13079002e256b thanks to @wout
